Repository itggot-TE4/Yabs, pull requests merged in 2018-11, with the labels that each got.

#25 21 navbar vuejs component
  frontend/src/App.vue
  frontend/src/components/HeaderNav.vue
Labels: enhancement

#29 Changed config.yml
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#30 Circleci patch 3
  .circleci/config.yml
  .gitignore
  backend/app/controllers/application_controller.rb
  backend/public/404.html
  backend/public/422.html
  backend/public/500.html
  backend/public/apple-touch-icon-precomposed.png
  backend/public/apple-touch-icon.png
  backend/public/favicon.ico
  backend/public/robots.txt
  frontend/vue.config.js
  tests/features/step_definitions/vue_steps.rb
  tests/features/vue_feature.feature
Labels: enhancement

#31 26 routher links
  frontend/src/App.vue
  frontend/src/components/HeaderNav.vue
  frontend/src/components/HelloWorld.vue
  frontend/src/router.ts
  frontend/src/views/About.vue
  frontend/src/views/Add.vue
  frontend/src/views/Find.vue
  frontend/src/views/Home.vue
  frontend/src/views/Profile.vue
  frontend/src/views/Start.vue
Labels: 3p, enhancement

#50 35 fetchusersgoogle
  .gitignore
  backend/Gemfile
  backend/app/jobs/data_fetch_job.rb
  backend/app/lib/assets/.keep
  backend/app/lib/google_api_client.rb
  backend/app/lib/tasks/.keep
  backend/config/application.rb
Labels: enhancement

#52 42 loans
  Directory.md
  backend/app/assets/javascripts/titles.coffee
  backend/app/assets/stylesheets/scaffolds.scss
  backend/app/assets/stylesheets/titles.scss
  backend/app/controllers/api/v1/.keep
  backend/app/controllers/api/v1/books_controller.rb
  backend/app/controllers/api/v1/loans_controller.rb
  backend/app/controllers/api/v1/roles_controller.rb
  backend/app/controllers/api/v1/titles_controller.rb
  backend/app/controllers/api/v1/users_controller.rb
  backend/app/helpers/titles_helper.rb
  backend/app/models/book.rb
  backend/app/models/loan.rb
  backend/app/models/role.rb
  backend/app/models/title.rb
  backend/app/models/user.rb
  backend/app/views/books/_book.json.jbuilder
  backend/app/views/books/index.json.jbuilder
  backend/app/views/books/show.json.jbuilder
  backend/app/views/loans/_loan.json.jbuilder
  backend/app/views/loans/index.json.jbuilder
  backend/app/views/loans/show.json.jbuilder
  backend/app/views/titles/_form.html.erb
  backend/app/views/titles/_title.json.jbuilder
  backend/app/views/titles/edit.html.erb
  backend/app/views/titles/index.html.erb
  backend/app/views/titles/index.json.jbuilder
  backend/app/views/titles/new.html.erb
  backend/app/views/titles/show.html.erb
  backend/app/views/titles/show.json.jbuilder
  backend/config/application.rb
  backend/config/routes.rb
  backend/db/migrate/20181120100040_change_primary_key_on_users.rb
  backend/db/migrate/20181120113857_create_titles.rb
  backend/db/migrate/20181120114623_create_books.rb
  backend/db/migrate/20181120115002_create_loans.rb
  backend/db/schema.rb
  backend/db/seeds.rb
  backend/test/controllers/books_controller_test.rb
  backend/test/controllers/loans_controller_test.rb
  backend/test/controllers/titles_controller_test.rb
  backend/test/fixtures/books.yml
  backend/test/fixtures/loans.yml
  backend/test/fixtures/titles.yml
  backend/test/models/book_test.rb
  backend/test/models/loan_test.rb
  backend/test/models/title_test.rb
Labels: loan

#53 51 merge role users
  backend/.DS_Store
  backend/app/controllers/api/v1/roles_controller.rb
  backend/app/jobs/data_fetch_job.rb
  backend/app/models/role.rb
  backend/app/models/user.rb
  backend/config/initializers/application_controller_renderer.rb
  backend/config/routes.rb
  backend/db/migrate/20181113120438_create_users.rb
  backend/db/migrate/20181113120534_create_roles.rb
  backend/db/schema.rb
  backend/db/seeds.rb
  backend/test/controllers/roles_controller_test.rb
  backend/test/fixtures/roles.yml
  backend/test/models/role_test.rb
Labels: enhancement

#49 48 test coverage
  .circleci/config.yml
  README.md
  backend/Gemfile
  backend/Gemfile.lock
  backend/bin/rails
  tests/features/support/env.rb
Labels: enhancement

#58 41 vuex
  backend/app/controllers/api/v1/books_controller.rb
  backend/app/controllers/api/v1/loans_controller.rb
  backend/app/controllers/api/v1/titles_controller.rb
  backend/app/controllers/api/v1/users_controller.rb
  backend/db/migrate/20181123113038_change_titles_type_column_name.rb
  backend/db/schema.rb
  backend/db/seeds.rb
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/books.ts
  frontend/src/api/loans.ts
  frontend/src/api/titles.ts
  frontend/src/api/users.ts
  frontend/src/components/HeaderNav.vue
  frontend/src/decorators.ts
  frontend/src/main.ts
  frontend/src/store/index.ts
  frontend/src/store/modules/books.ts
  frontend/src/store/modules/loans.ts
  frontend/src/store/modules/titles.ts
  frontend/src/store/modules/users.ts
  tsconfig.json
Labels: feature, loan

#57 38 jsonforcards
  backend/app/controllers/api/v1/users_controller.rb
  backend/app/models/user.rb
  backend/db/migrate/20181121120753_create_active_storage_tables.active_storage.rb
  backend/db/schema.rb
Labels: cig, enhancement

#62 Should be catch instead of then
  frontend/src/store/modules/books.ts
  frontend/src/store/modules/loans.ts
  frontend/src/store/modules/titles.ts
  frontend/src/store/modules/users.ts
Labels: bug

#66 added "klass" to database
  backend/app/jobs/data_fetch_job.rb
  backend/db/migrate/20181113120438_create_users.rb
  backend/db/schema.rb
Labels: enhancement
