Repository itggot-TE4/Yabs, pull requests merged in 2018-12, with the labels that each got.

#78 fixed ALL linting errors in the universe
  frontend/src/api/books.ts
  frontend/src/api/loans.ts
  frontend/src/api/titles.ts
  frontend/src/api/users.ts
  frontend/src/components/CanvasContainer.vue
  frontend/src/components/CigForm.vue
  frontend/src/decorators.ts
  frontend/src/main.ts
  frontend/src/store/index.ts
  frontend/src/store/modules/books.ts
  frontend/src/store/modules/loans.ts
  frontend/src/store/modules/titles.ts
  frontend/src/store/modules/users.ts
Labels: enhancement

#75 added removed user function
  backend/app/jobs/data_fetch_job.rb
Labels: enhancement

#80 67 profile page
  backend/db/schema.rb
  frontend/src/App.vue
  frontend/src/components/AddLoan.vue
  frontend/src/components/ReacentLoan.vue
  frontend/src/views/Add.vue
  frontend/src/views/Profile.vue
Labels: feature

#82 add lint job
  .circleci/config.yml
  frontend/package.json
  frontend/src/components/LoaningForm.vue
Labels: enhancement

#85 fixed bug
  frontend/src/components/RecentLoan.vue
  frontend/src/views/Add.vue
  frontend/src/views/Profile.vue
Labels: bug

#79 14 start page
  frontend/public/index.html
  frontend/src/views/Start.vue
Labels: enhancement

#88 40 action handlers
  .gitignore
  backend/.DS_Store
  backend/app/controllers/api/v1/users_controller.rb
  backend/app/models/book.rb
  backend/app/models/loan.rb
  backend/config/application.rb
  backend/config/routes.rb
  backend/db/migrate/20181120100040_change_primary_key_on_users.rb
  backend/db/migrate/20181120114623_create_books.rb
  backend/db/migrate/20181120115002_create_loans.rb
  backend/db/schema.rb
  backend/db/seeds.rb
  frontend/src/api/books.ts
  frontend/src/api/users.ts
  frontend/src/components/CigForm.vue
  frontend/src/components/LoaningForm.vue
  frontend/src/store/modules/books.ts
  frontend/src/store/modules/loans.ts
  frontend/src/store/modules/titles.ts
  frontend/src/store/modules/users.ts
Labels: enhancement

#89 update loans table and seeds file
  backend/app/controllers/api/v1/loans_controller.rb
  backend/db/migrate/20181205140748_add_expiration_date_column_to_loans.rb
  backend/db/migrate/20181205140850_rename_loans_return_at_to_returned_at.rb
  backend/db/schema.rb
  backend/db/seeds.rb
Labels: enhancement

#92 Fixed book and titel forms
  frontend/src/components/AddingForm.vue
  frontend/src/components/CigForm.vue
  frontend/src/components/DropDownType.vue
  frontend/src/components/RecentTitel.vue
  frontend/src/components/TitelForm.vue
  frontend/src/views/Add.vue
Labels: feature

#94 93 fixdatabaseelev
  backend/app/jobs/data_fetch_job.rb
Labels: 1p, bug

#65 60 search page
  backend/db/migrate/20181113120438_create_users.rb
  backend/db/schema.rb
  frontend/src/App.vue
  frontend/src/components/AllBooks.vue
  frontend/src/components/DropdownFind.vue
  frontend/src/components/LoanSearch.vue
  frontend/src/components/MainTable.vue
  frontend/src/views/Find.vue
Labels: enhancement

#100 77 integratecanvas
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/background.png
  frontend/src/assets/logo.png
  frontend/src/assets/profil.jpg
  frontend/src/components/CanvasContainer.vue
  frontend/src/components/CigCanvas.vue
  frontend/src/components/CigForm.vue
  frontend/src/components/DropDownType.vue
  frontend/src/main.ts
  frontend/src/store/modules/users.ts
  frontend/src/views/Add.vue
  frontend/src/vue-resize-directive.d.ts
  package-lock.json
Labels: feature

#101 47 clean up routes
  frontend/src/router.ts
  frontend/src/views/index.ts
Labels: enhancement

#105 Fixed type bug
  frontend/src/components/DropDownType.vue
  frontend/src/views/Add.vue
Labels: bug

#107 Tests for the Start page
  Gemfile.lock
  tests/features/StartAdd.feature
  tests/features/StartFind.feature
  tests/features/StartProfile.feature
  tests/features/step_definitions/StartTests_steps.rb
  tests/features/step_definitions/step_defitions.rb
  tests/features/step_definitions/test_steps.rb
  tests/features/step_definitions/vue_steps.rb
  tests/features/vue_feature.feature
Labels: feature

#109 103 vuex promises
  frontend/src/components/RecentLoan.vue
  frontend/src/store/modules/books.ts
  frontend/src/store/modules/loans.ts
  frontend/src/store/modules/titles.ts
  frontend/src/store/modules/users.ts
Labels: enhancement

#115 112 add loading icon
  backend/app/controllers/api/v1/titles_controller.rb
  frontend/src/components/AllBooks.vue
  frontend/src/components/LoadingIcon.vue
  frontend/src/components/RecentLoan.vue
  frontend/src/views/Add.vue
  frontend/src/views/Find.vue
  frontend/src/views/Start.vue
  tests/features/AddIDcard.feature
  tests/features/AddLoan.feature
  tests/features/AddTitle.feature
  tests/features/step_definitions/AddIDcard_steps.rb
  tests/features/step_definitions/StartTests_steps.rb
Labels: enhancement
