Repository itggot-TE4/Yabs, pull requests merged in 2019-12, with the labels that each got.

#155 app not overwritten and unnecessary files removed, vuetify added
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.vue
  frontend/src/assets/logo.svg
  frontend/src/main.ts
  frontend/src/plugins/vuetify.ts
  frontend/tsconfig.json
  frontend/vue.config.js
  frontend/yarn.lock
Labels: 1p, enhancement, red

#158 Feature/138 vuex module decorators
  frontend/package.json
  frontend/src/components/AddingForm.vue
  frontend/src/components/AllBooks.vue
  frontend/src/components/CigCanvas.vue
  frontend/src/components/CigForm.vue
  frontend/src/components/GoogleLogin.vue
  frontend/src/components/HeaderNav.vue
  frontend/src/components/LoaningForm.vue
  frontend/src/components/MainTable.vue
  frontend/src/components/RecentBook.vue
  frontend/src/components/RecentLoan.vue
  frontend/src/components/RecentTitel.vue
  frontend/src/components/TitelForm.vue
  frontend/src/components/__tests__/HeaderNav.spec.ts
  frontend/src/components/__tests__/__snapshots__/HeaderNav.spec.ts.snap
  frontend/src/helpers/testFactoryHelpers.ts
  frontend/src/store/index.ts
  frontend/src/store/modules/BooksModule.ts
  frontend/src/store/modules/LoansModule.ts
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/store/modules/UsersModule.ts
  frontend/src/store/modules/books.ts
  frontend/src/store/modules/loans.ts
  frontend/src/store/modules/titles.ts
  frontend/src/store/modules/users.ts
  frontend/src/views/Profile.vue
  frontend/yarn.lock
Labels: 5p, enhancement, green

#152 Boilerplate/149 docsify
  .gitignore
  docs/.nojekyll
  docs/README.md
  docs/index.html
  package.json
Labels: docs

#169 Refactored AddingForm and changed name to CreateBookFormComponent.
  frontend/src/App.vue
  frontend/src/components/AddingForm.vue
  frontend/src/components/CreateBookFormComponent.vue
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/views/Add.vue
Labels: enhancement, green

#172 Updated integrations test
  .github/unit.yml
  .github/workflows/integration.yml
Labels: bug

#176 Feature/175 improve loading perfomance
  frontend/src/api/users.ts
  frontend/src/components/__tests__/HeaderNav.spec.ts
  frontend/src/components/__tests__/__snapshots__/HeaderNav.spec.ts.snap
  frontend/src/helpers/convertArrayToNested.ts
  frontend/src/store/modules/BooksModule.ts
  frontend/src/store/modules/LoansModule.ts
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/store/modules/UsersModule.ts
  frontend/src/views/Profile.vue
  frontend/src/views/Start.vue
Labels: 8p, enhancement, green

#174 Fixed the Pundit CRUD authorization
  backend/app/controllers/api/v1/loans_controller.rb
  backend/app/controllers/api/v1/users_controller.rb
  backend/app/controllers/application_controller.rb
  backend/app/policies/application_policy.rb
  backend/app/policies/loan_policy.rb
  backend/app/policies/user_policy.rb
Labels: 5p, blue, feature

#180 Forgot to push the last changes on the pull request related to #160
  backend/app/controllers/api/v1/users_controller.rb
  backend/app/controllers/application_controller.rb
Labels: 3p, blue, enhancement

#173 144 changed from bootstrap to vuetify
  frontend/public/index.html
  frontend/src/components/AddLoan.vue
  frontend/src/components/AllBooks.vue
  frontend/src/components/CanvasContainer.vue
  frontend/src/components/CigCanvas.vue
  frontend/src/components/CigForm.vue
  frontend/src/components/DropDownType.vue
  frontend/src/components/DropdownFind.vue
  frontend/src/components/LoaningForm.vue
  frontend/src/components/MainTable.vue
  frontend/src/components/TitelForm.vue
  frontend/src/views/Add.vue
  frontend/src/views/Find.vue
  frontend/src/views/Start.vue
Labels: blue, enhancement, green, red

#168 added rules to tslint
  frontend/.eslintrc.js
  frontend/babel.config.js
  frontend/package.json
  frontend/src/App.vue
  frontend/src/api/books.ts
  frontend/src/api/loans.ts
  frontend/src/api/titles.ts
  frontend/src/api/users.ts
  frontend/src/components/CreateBookFormComponent.vue
  frontend/src/components/LoanSearch.vue
  frontend/src/components/TitelForm.vue
  frontend/src/components/__tests__/HeaderNav.spec.ts
  frontend/src/helpers/convertArrayToNested.ts
  frontend/src/shims-tsx.d.ts
  frontend/src/store/index.ts
  frontend/src/store/modules/LoansModule.ts
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/store/modules/UsersModule.ts
  frontend/src/views/Add.vue
  frontend/src/views/Find.vue
  frontend/src/views/Profile.vue
  frontend/src/views/Start.vue
  frontend/tslint.json
  frontend/yarn.lock
Labels: boilerplate

#182 181 No more pug.
  frontend/src/components/AddLoan.vue
  frontend/src/components/AllBooks.vue
  frontend/src/components/CanvasContainer.vue
  frontend/src/components/CigCanvas.vue
  frontend/src/components/CigForm.vue
  frontend/src/components/CreateBookFormComponent.vue
  frontend/src/components/DropDownType.vue
  frontend/src/components/DropdownFind.vue
  frontend/src/components/GoogleLogin.vue
  frontend/src/components/HeaderNav.vue
  frontend/src/components/LoadingIcon.vue
  frontend/src/components/LoanSearch.vue
  frontend/src/components/LoaningForm.vue
  frontend/src/components/MainTable.vue
  frontend/src/components/RecentBook.vue
  frontend/src/components/RecentLoan.vue
  frontend/src/components/RecentTitel.vue
  frontend/src/components/TitelForm.vue
  frontend/src/store/modules/BooksModule.ts
  frontend/src/views/Add.vue
  frontend/src/views/Find.vue
  frontend/src/views/Profile.vue
  frontend/src/views/Start.vue
Labels: enhancement, frontend, green

#178 162 Post empty resources
  frontend/src/components/CreateBookFormComponent.vue
  frontend/src/components/LoaningForm.vue
  frontend/src/components/TitelForm.vue
  frontend/src/store/modules/BooksModule.ts
Labels: bug, green

#188 Fixed all type def errors
  frontend/babel.config.js
  frontend/jest.config.js
  frontend/src/components/AddLoan.vue
  frontend/src/components/AllBooks.vue
  frontend/src/components/CanvasContainer.vue
  frontend/src/components/CigCanvas.vue
  frontend/src/components/CigForm.vue
  frontend/src/components/CreateBookFormComponent.vue
  frontend/src/components/DropDownType.vue
  frontend/src/components/DropdownFind.vue
  frontend/src/components/GoogleLogin.vue
  frontend/src/components/HeaderNav.vue
  frontend/src/components/LoadingIcon.vue
  frontend/src/components/LoanSearch.vue
  frontend/src/components/LoaningForm.vue
  frontend/src/components/MainTable.vue
  frontend/src/components/RecentBook.vue
  frontend/src/components/RecentLoan.vue
  frontend/src/components/RecentTitel.vue
  frontend/src/components/TitelForm.vue
  frontend/src/views/Add.vue
  frontend/src/views/Find.vue
  frontend/src/views/Profile.vue
  frontend/src/views/Start.vue
  frontend/vue.config.js
Labels: 3p, enhancement, green, red

#184 Feature/133 migrate search functionality
  frontend/src/components/SearchListComponent.vue
Labels: blue, frontend

#195 updated linting severity to warnings
  frontend/.eslintrc.js
Labels: boilerplate

#193 Fixed 170 and you can now post the type.
  backend/app/controllers/api/v1/titles_controller.rb
  frontend/src/components/TitelFormComponent.vue
  frontend/src/components/__tests__/__snapshots__/HeaderNav.spec.ts.snap
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/views/Add.vue
Labels: blue, bug, green

#191 Feature/142 assign roles
  backend/app/controllers/application_controller.rb
  backend/app/jobs/data_fetch_job.rb
  backend/app/models/user.rb
  backend/db/migrate/20191211142725_change_user_role_to_be_integer.rb
  backend/db/schema.rb
Labels: enhancement

#194 Boilerplate/164 seed more usefull data
  Gemfile
  backend/app/controllers/api/v1/loans_controller.rb
  backend/db/seeds.rb
  backend/test/controllers/loans_controller_test.rb
  backend/test/controllers/users_controller_test.rb
  backend/test/fixtures/books.yml
  backend/test/fixtures/loans.yml
  backend/test/fixtures/titles.yml
  backend/test/fixtures/users.yml
Labels: 1p, blue, boilerplate

#198 Added views for all subpages for the admin page & added navigation to…
  frontend/src/App.vue
  frontend/src/components/CreateBookFormComponent.vue
  frontend/src/components/DropDownType.vue
  frontend/src/components/HeaderNav.vue
  frontend/src/router.ts
  frontend/src/views/AdminBooksView.vue
  frontend/src/views/AdminCardsView.vue
  frontend/src/views/AdminIndexView.vue
  frontend/src/views/AdminLoansView.vue
  frontend/src/views/AdminTitlesView.vue
  frontend/src/views/AdminView.vue
  frontend/src/views/Start.vue
  frontend/src/views/index.ts
Labels: 5p, feature, red

#201 Feature/186 vuetify profile page
  backend/app/policies/user_policy.rb
  frontend/src/components/CreateBookFormComponent.vue
  frontend/src/components/HeaderNav.vue
  frontend/src/components/LoaningForm.vue
  frontend/src/components/RecentLoan.vue
  frontend/src/store/modules/LoansModule.ts
  frontend/src/store/modules/UsersModule.ts
  frontend/src/views/Profile.vue
  frontend/yarn.lock
Labels: frontend, red

#199 Feature/159 refactor navbar
  frontend/src/App.vue
  frontend/src/api/loans.ts
  frontend/src/api/users.ts
  frontend/src/components/CreateBookFormComponent.vue
  frontend/src/components/GoogleLogin.vue
  frontend/src/components/LoaningForm.vue
  frontend/src/components/NavbarComponent.vue
  frontend/src/components/RecentLoan.vue
  frontend/src/components/SearchListComponent.vue
  frontend/src/components/__tests__/NavbarComponent.spec.ts
  frontend/src/components/__tests__/__snapshots__/NavbarComponent.spec.ts.snap
  frontend/src/store/modules/LoansModule.ts
  frontend/src/store/modules/UsersModule.ts
  frontend/src/views/Add.vue
  frontend/src/views/AdminBooksView.vue
  frontend/src/views/AdminCardsView.vue
  frontend/src/views/AdminIndexView.vue
  frontend/src/views/AdminLoansView.vue
  frontend/src/views/AdminTitlesView.vue
  frontend/src/views/AdminView.vue
  frontend/src/views/Profile.vue
  frontend/yarn.lock
  tsconfig.json
Labels: enhancement, frontend, green

#204 Feature/202 rewrite admin subpages
  frontend/src/App.vue
  frontend/src/components/BookFormComponent.vue
  frontend/src/components/BookListComponent.vue
  frontend/src/components/CanvasContainer.vue
  frontend/src/components/CardFormComponent.vue
  frontend/src/components/CreateBookFormComponent.vue
  frontend/src/components/LoanFormComponent.vue
  frontend/src/components/LoanListComponent.vue
  frontend/src/components/RecentBook.vue
  frontend/src/components/RecentLoan.vue
  frontend/src/components/RecentTitel.vue
  frontend/src/components/TitleFormComponent.vue
  frontend/src/components/TitleListComponent.vue
  frontend/src/router.ts
  frontend/src/store/modules/BooksModule.ts
  frontend/src/store/modules/LoansModule.ts
  frontend/src/views/Add.vue
  frontend/src/views/AdminBooksView.vue
  frontend/src/views/AdminCardsView.vue
  frontend/src/views/AdminDashboardView.vue
  frontend/src/views/AdminLoansView.vue
  frontend/src/views/AdminTitlesView.vue
  frontend/src/views/AdminView.vue
  frontend/src/views/Profile.vue
  frontend/src/views/Start.vue
  frontend/src/views/index.ts
Labels: 3p, enhancement, frontend, green

#196 Hotfix/190 fix current user mock
  backend/app/controllers/api/v1/loans_controller.rb
  backend/app/controllers/api/v1/users_controller.rb
  backend/app/policies/loan_policy.rb
  backend/app/policies/user_policy.rb
  backend/test/fixtures/books.yml
Labels: 3p, blue, bug

#183 Feature/145 convert to cypress
  .github/workflows/integration.yml
  Gemfile
  Gemfile.lock
  backend/Gemfile
  cypress.json
  frontend/.eslintrc.js
  frontend/cypress/integration/AddIDCard.spec.js
  frontend/cypress/integration/FirstPageTests.spec.js
  frontend/cypress/integration/sample_spec.js
  frontend/cypress/screenshots/AddIDCard.spec.js/Going to the add page -- Going to Cards in menu -- before each hook (failed).png
  frontend/cypress/screenshots/FirstPageTests.spec.js/Going to the first page -- Click on Admin on first page and loan out an existing book -- before each hook (failed).png
  frontend/cypress/videos/AddIDCard.spec.js.mp4
  frontend/cypress/videos/FirstPageTests.spec.js.mp4
  frontend/package.json
  frontend/src/components/LoanFormComponent.vue
  frontend/src/store/modules/LoansModule.ts
  frontend/src/store/modules/UsersModule.ts
  frontend/src/views/AdminView.vue
  frontend/src/views/Profile.vue
  frontend/src/views/Start.vue
  frontend/yarn.lock
  tests/features/AddIDcard.feature
  tests/features/AddLoan.feature
  tests/features/AddTitle.feature
  tests/features/StartAdd.feature
  tests/features/StartFind.feature
  tests/features/StartProfile.feature
  tests/features/step_definitions/AddIDcard_steps.rb
  tests/features/step_definitions/StartTests_steps.rb
  tests/features/support/env.rb
Labels: 5p, enhancement, red

#205 Feature/185 convert find view
  backend/.DS_Store
  frontend/.gitignore
  frontend/src/components/AllBooks.vue
  frontend/src/components/BookFormComponent.vue
  frontend/src/components/BookListComponent.vue
  frontend/src/components/CardFormComponent.vue
  frontend/src/components/DropdownFind.vue
  frontend/src/components/LoanListComponent.vue
  frontend/src/components/LoanSearch.vue
  frontend/src/components/MainTable.vue
  frontend/src/components/SearchListComponent.vue
  frontend/src/components/TitleFormComponent.vue
  frontend/src/components/TitleListComponent.vue
  frontend/src/router.ts
  frontend/src/views/AdminBooksView.vue
  frontend/src/views/AdminCardsView.vue
  frontend/src/views/AdminLoansView.vue
  frontend/src/views/AdminTitlesView.vue
  frontend/src/views/AdminView.vue
  frontend/src/views/Find.vue
  frontend/src/views/FindView.vue
  frontend/src/views/index.ts
Labels: blue, feature, frontend, red

#221 Removed duplicated fields
  frontend/src/components/LoanFormComponent.vue
Labels: bug

#223 easier to go from test to dev, and also if we ever change the routes
  .github/workflows/integration.yml
  backend/Gemfile.lock
  backend/test/fixtures/books.yml
  backend/test/fixtures/loans.yml
  backend/test/fixtures/titles.yml
  backend/test/fixtures/users.yml
  frontend/cypress/helper.js
  frontend/cypress/integration/AddIDCard.spec.js
  frontend/cypress/integration/FirstPageTests.spec.js
  frontend/cypress/screenshots/AddIDCard.spec.js/An uncaught error was detected outside of a test (failed).png
  frontend/cypress/screenshots/AddIDCard.spec.js/Going to the add page -- Going to Cards in menu -- before each hook (failed).png
  frontend/cypress/screenshots/FirstPageTests.spec.js/An uncaught error was detected outside of a test (failed).png
  frontend/cypress/screenshots/FirstPageTests.spec.js/Going to the first page -- Click on Admin on first page and loan out an existing book -- before each hook (failed).png
  frontend/cypress/videos/AddIDCard.spec.js.mp4
  frontend/cypress/videos/FirstPageTests.spec.js.mp4
Labels: 1p, boilerplate, red

#218 Split module state into own attributes
  frontend/src/components/HeaderNav.vue
  frontend/src/components/NavbarComponent.vue
  frontend/src/store/modules/BooksModule.ts
  frontend/src/store/modules/LoansModule.ts
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/store/modules/UsersModule.ts
  frontend/src/views/Start.vue
  frontend/yarn.lock
Labels: enhancement, frontend, green, red

#227 Added color on active link
  frontend/src/views/AdminView.vue
Labels: 1p

#228 Bug/226 path argument error
  frontend/package.json
  frontend/src/components/SearchListComponent.vue
  frontend/src/views/AdminView.vue
  frontend/src/views/Profile.vue
  frontend/yarn.lock
Labels: bug

#232 made eslint see red == transformed warn -> error
  .github/workflows/integration.yml
  frontend/.eslintrc.js
  frontend/src/components/NavbarComponent.vue
Labels: enhancement

#231 Fixed bug
  frontend/src/views/Start.vue
Labels: bug

#234 Removed duplication
  frontend/src/components/BookListComponent.vue
  frontend/src/components/ListComponent.vue
  frontend/src/components/LoanListComponent.vue
  frontend/src/components/TitleListComponent.vue
  frontend/src/views/FindView.vue
Labels: 3p, blue, enhancement, frontend

#241 Changed errors to warn
  frontend/.eslintrc.js
Labels: enhancement

#233 Fixed unittests in frontend
  frontend/src/components/__tests__/HeaderNav.spec.ts
  frontend/src/components/__tests__/NavbarComponent.spec.ts
  frontend/src/components/__tests__/__snapshots__/NavbarComponent.spec.ts.snap
  frontend/src/helpers/testFactoryHelpers.ts
Labels: bug

#244 Tests fixed and a few linterwarnings fixed in loanformcomponent
  frontend/cypress/integration/FirstPageTests.spec.js
  frontend/cypress/screenshots/AddIDCard.spec.js/An uncaught error was detected outside of a test (failed).png
  frontend/cypress/screenshots/FirstPageTests.spec.js/An uncaught error was detected outside of a test (failed).png
  frontend/cypress/videos/AddIDCard.spec.js.mp4
  frontend/cypress/videos/FirstPageTests.spec.js.mp4
  frontend/src/components/LoanFormComponent.vue
  frontend/src/store/modules/LoansModule.ts
Labels: 1p, bug, red

#230 Google API with books works now
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/controllers/api/v1/titles_controller.rb
  backend/db/migrate/20191216135511_add_columns_to_title.rb
  backend/db/migrate/20191216135730_drop_title_from_title.rb
  backend/db/schema.rb
  backend/db/seeds.rb
  backend/test/fixtures/books.yml
  backend/test/fixtures/loans.yml
  backend/test/fixtures/titles.yml
  backend/test/fixtures/users.yml
Labels: 3p, backend, green

#247 #208/ Able to add books and titles with cypress
  frontend/cypress/integration/createTitleAndBooks.js
  frontend/src/components/BookFormComponent.vue
  frontend/src/components/TitleFormComponent.vue
Labels: bug, green

#248 added max warnings to lintnf
  frontend/package.json
Labels: enhancement

#251 BUG/249/Able to see the right values for ISBN and Type
  frontend/src/components/TitleListComponent.vue
Labels: bug, green

#236 Add documentation to master branch
  .gitignore
  docs/.nojekyll
  docs/README.md
  docs/index.html
  package.json
Labels: boilerplate, docs

#256 You can now see the loans where you are the loaner.
  frontend/src/components/LoanListComponent.vue
Labels: bug, green

#245 Bugfix/222/tests throw no method error
  backend/Gemfile.lock
  backend/app/controllers/api/v1/users_controller.rb
  backend/app/policies/user_policy.rb
  backend/db/seeds.rb
  backend/test/controllers/users_controller_test.rb
  backend/test/fixtures/books.yml
  backend/test/fixtures/loans.yml
  backend/test/fixtures/titles.yml
  backend/test/fixtures/users.yml
Labels: backend, bug

#258 Fixed styling
  frontend/src/components/CanvasContainer.vue
  frontend/src/components/CigCanvas.vue
Labels: frontend, red

#243 Feature/237 frontend roles
  frontend/src/components/CigCanvas.vue
  frontend/src/components/NavbarComponent.vue
  frontend/src/helpers/RoleChecker.ts
  frontend/src/store/__tests__/RoleChecker.spec.ts
  frontend/src/store/modules/UsersModule.ts
  frontend/src/views/FindView.vue
  frontend/src/views/Profile.vue
Labels: 3p, enhancement, help wanted

#259 List of users now shows users
  frontend/src/components/CigCanvas.vue
  frontend/src/views/AdminCardsView.vue
Labels: bug, frontend, green

#266 Fixed errors in cigcanvas
  frontend/src/components/CigCanvas.vue
Labels: bug, frontend, red

#268 Fixed lint in API services & modules
  frontend/src/api/books.ts
  frontend/src/api/loans.ts
  frontend/src/api/titles.ts
  frontend/src/api/users.ts
  frontend/src/components/BookFormComponent.vue
  frontend/src/components/CigCanvas.vue
  frontend/src/components/LoanFormComponent.vue
  frontend/src/store/modules/BooksModule.ts
  frontend/src/store/modules/LoansModule.ts
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/store/modules/UsersModule.ts
Labels: 3p, enhancement, frontend, green

#253 Fixed the documentation in the entire application
  backend/app/controllers/api/v1/books_controller.rb
  backend/app/controllers/api/v1/loans_controller.rb
  backend/app/controllers/api/v1/titles_controller.rb
  backend/app/controllers/application_controller.rb
  backend/app/models/user.rb
  backend/app/policies/application_policy.rb
  backend/app/policies/loan_policy.rb
  backend/app/policies/user_policy.rb
  frontend/src/components/BookFormComponent.vue
  frontend/src/components/BookListComponent.vue
  frontend/src/components/CanvasContainer.vue
  frontend/src/components/CardFormComponent.vue
  frontend/src/components/CigCanvas.vue
  frontend/src/components/GoogleLogin.vue
  frontend/src/components/LoanFormComponent.vue
  frontend/src/components/LoanListComponent.vue
  frontend/src/components/NavbarComponent.vue
  frontend/src/components/TitleFormComponent.vue
  frontend/src/components/TitleListComponent.vue
  frontend/src/views/AdminBooksView.vue
  frontend/src/views/AdminCardsView.vue
  frontend/src/views/AdminLoansView.vue
  frontend/src/views/AdminTitlesView.vue
  frontend/src/views/AdminView.vue
  frontend/src/views/Start.vue
Labels: 5p, blue, docs

#272 Feature/269 helper fun arr
  frontend/src/helpers/__tests__/RoleChecker.spec.ts
  frontend/src/helpers/__tests__/convertArrayToNested.spec.ts
  frontend/src/helpers/__tests__/convertNestedToArray.spec.ts
  frontend/src/helpers/convertArrayToNested.ts
  frontend/src/helpers/convertNestedToArray.ts
  frontend/src/store/modules/BooksModule.ts
  frontend/src/store/modules/LoansModule.ts
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/store/modules/UsersModule.ts
Labels: 3p, enhancement, frontend, green

#277 Added typedefs etc.
  frontend/src/api/users.ts
  frontend/src/components/BookFormComponent.vue
  frontend/src/components/CanvasContainer.vue
  frontend/src/components/CardFormComponent.vue
  frontend/src/components/CigCanvas.vue
  frontend/src/components/LoanFormComponent.vue
  frontend/src/components/LoanListComponent.vue
  frontend/src/components/NavbarComponent.vue
  frontend/src/components/TitleFormComponent.vue
  frontend/src/components/TitleListComponent.vue
  frontend/src/store/modules/BooksModule.ts
  frontend/src/store/modules/LoansModule.ts
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/store/modules/UsersModule.ts
  frontend/src/views/AdminBooksView.vue
  frontend/src/views/AdminCardsView.vue
  frontend/src/views/AdminLoansView.vue
  frontend/src/views/AdminTitlesView.vue
  frontend/src/views/AdminView.vue
Labels: 3p, enhancement, frontend, green

#278 Added types file and changed in all affected files
  frontend/src/api/books.ts
  frontend/src/api/loans.ts
  frontend/src/api/titles.ts
  frontend/src/api/users.ts
  frontend/src/components/BookFormComponent.vue
  frontend/src/components/LoanFormComponent.vue
  frontend/src/components/TitleFormComponent.vue
  frontend/src/store/modules/BooksModule.ts
  frontend/src/store/modules/LoansModule.ts
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/store/modules/UsersModule.ts
  frontend/src/types.ts
Labels: enhancement, frontend, green

#279 Feature/267 fixtures should work like snapshots
  backend/db/seeds.rb
  backend/test/fixtures/books.yml
  backend/test/fixtures/loans.yml
  backend/test/fixtures/reviews.yml
  backend/test/fixtures/titles.yml
  backend/test/fixtures/users.yml
Labels: 3p, blue, boilerplate

#282 changed imports to match the new interface file
  frontend/src/helpers/RoleChecker.ts
  frontend/src/views/Profile.vue
Labels: bug

#290 fixed errors with Mattis
  frontend/src/components/CigCanvas.vue
  frontend/src/store/modules/UsersModule.ts
Labels: frontend, red

#284 added integration run on merge with develop
  .github/workflows/integration.yml
Labels: enhancement

#295 roleastext now able to take a user as input
  frontend/src/helpers/RoleChecker.ts
  frontend/src/helpers/__tests__/RoleChecker.spec.ts
Labels: 1p, enhancement, red

#297 updated fixtures to load into test db
  .github/workflows/integration.yml
Labels: bug
