Repository itggot-TE4/Yabs, pull requests merged in 2020-12, with the labels that each got.

#351 Add composition API to frontend project
  frontend/package.json
  frontend/src/components/TitleFormComponent.vue
  frontend/src/helpers/testFactoryHelpers.ts
  frontend/src/main.ts
  frontend/yarn.lock
Labels: type:refactor 🔨

#410 The cypress test will now fail if the title is not actually created in the create title test
  frontend/cypress/integration/createTitleAndBooks.js
  frontend/src/components/ListComponent.vue
Labels: type:test🚨

#452 Improve development environment with VSCode
  .editorconfig
  README.md
  frontend/tsconfig.json
  vetur.config.js
Labels: type:enhancement💫

#449 Resolved failing integration tests (e2e)
  backend/app/controllers/api/v1/titles_controller.rb
  frontend/cypress/integration/createTitleAndBooks.js
  frontend/src/components/TitleFormComponent.vue
  frontend/src/components/__tests__/TitleFormComponent.spec.ts
  frontend/src/services/api/subjects.ts
  frontend/src/types.ts
Labels: type:bug🐛

#444 Test for adding book loan
  frontend/cypress/cypress.json
  frontend/cypress/integration/addLoan.js
  frontend/src/components/ReturnLoanComponent.vue
Labels: type:test🚨

#462 Test for rendering specific user and all users
  backend/test/controllers/users_controller_test.rb
Labels: type:test🚨

#493 Refactored LibraryView.vue and related components to Composition API.
  frontend/src/components/LibraryLoanComponent.vue
  frontend/src/components/ListComponent.vue
  frontend/src/components/LoanListComponent.vue
  frontend/src/components/ReturnLoanComponent.vue
  frontend/src/components/TitleListComponent.vue
  frontend/src/router.ts
  frontend/src/views/LibraryView.vue
Labels: type:refactor 🔨

#494 Bug/403 seeder
  README.md
  backend/db/seeds.rb
Labels: comp: backend

#502 Added update title interface
  backend/app/controllers/api/v1/titles_controller.rb
  frontend/cypress/integration/updateTitle.js
  frontend/src/components/ListComponent.vue
  frontend/src/components/TitleFormComponent.vue
  frontend/src/components/TitleListComponent.vue
  frontend/src/router.ts
  frontend/src/services/api/titles.ts
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/views/AdminTitlesEditView.vue
  frontend/src/views/index.ts
Labels: comp: frontend

#507 refactored navbar component
  frontend/src/components/NavbarComponent.vue
  frontend/src/components/__tests__/NavbarComponent.spec.ts
  frontend/src/main.ts
Labels: type:refactor 🔨

#523 Refactored AdminView and AdminUsersView
  frontend/src/router.ts
  frontend/src/views/AdminUsersView.vue
  frontend/src/views/AdminView.vue
  frontend/src/views/index.ts
Labels: type:refactor 🔨

#530 Feature/513 search by barcode
  frontend/src/components/LoanListComponent.vue
Labels: comp: frontend, type:feature✨

#549 User profile view and role display
  frontend/src/components/CigCanvas.vue
  frontend/src/helpers/roleToText.ts
  frontend/src/types.ts
  frontend/src/views/AdminUsersView.vue
  frontend/src/views/ProfileView.vue
  frontend/src/views/__tests__/ProfileView.spec.ts
Labels: type:enhancement💫

#552 Feature/511 update status when returning book
  frontend/cypress/integration/ReturnBook.spec.js
  frontend/src/components/ReturnLoanComponent.vue
  frontend/src/components/__tests__/ReturnBookComponent.spec.ts
Labels: comp: frontend, type:feature✨

#506 return functionality for books in adminview
  frontend/src/views/AdminLoansView.vue
Labels: comp: frontend, type:feature✨

#558 working husky pre-commit
  .husky/.gitignore
  .husky/pre-commit
  package.json
  yarn.lock
Labels: comp: frontend, type:feature✨

#564 Refactored AdminCardsView and its components
  frontend/src/components/CanvasContainer.vue
  frontend/src/components/CardFormComponent.vue
  frontend/src/components/CigCanvas.vue
  frontend/src/views/AdminCardsView.vue
  frontend/src/views/__tests__/AdminCardView.spec.ts
Labels: type:refactor 🔨

#565 Added tests to AdminLoansView
  frontend/src/views/__tests__/AdminLoansView.spec.ts
Labels: type:test🚨

#566 Refactor book components
  frontend/src/components/BookConditionComponent.vue
  frontend/src/components/BookFormComponent.vue
  frontend/src/components/BookListComponent.vue
  frontend/src/components/__tests__/BookFormComponent.spec.ts
Labels: type:refactor 🔨

#570 Fixed the errors in two list components
  frontend/src/components/LoanListComponent.vue
  frontend/src/components/TitleListComponent.vue
Labels: comp: frontend

#562 Implemented test for AdminDashboardView
  frontend/src/views/__tests__/AdminDashboardView.spec.ts
Labels: type:test🚨

#569 Added unit tests for AdminTitlesView
  frontend/src/views/__tests__/AdminTitlesView.spec.ts
Labels: type:test🚨

#557 Refactored AdminDashboardView
  frontend/src/views/AdminDashboardView.vue
Labels: type:refactor 🔨

#575 Refactored EditBookView and fixed its functionality
  frontend/src/components/BookConditionComponent.vue
  frontend/src/router.ts
  frontend/src/views/EditBookView.vue
Labels: type:refactor 🔨

#574 Implemented unit tests for AdminView
  frontend/src/views/__tests__/AdminView.spec.ts
Labels: type:test🚨

#571 Added force click to updateTitle test
  frontend/cypress/integration/updateTitle.js
Labels: type:bug🐛

#578 Hotfix for typeerror
  frontend/src/views/__tests__/AdminDashboardView.spec.ts
Labels: priority: highest, type:bug🐛, type:test🚨

#576 Implemented unit tests for AdminUsersView
  frontend/src/views/__tests__/AdminUsersView.spec.ts
Labels: type:test🚨

#580 Test/471 test for edit book view
  frontend/src/store/modules/BooksModule.ts
  frontend/src/views/__tests__/EditBookView.spec.ts
Labels: type:test🚨

#584 Refactored list component to composition API
  frontend/src/components/ListComponent.vue
  frontend/src/components/__tests__/ListComponent.spec.ts
Labels: comp: frontend, type:refactor 🔨

#561 refactored profile view
  frontend/src/types.ts
  frontend/src/views/ProfileView.vue
  frontend/src/views/__tests__/ProfileView.spec.ts
Labels: type:refactor 🔨

#553 Moving to postgres, BREAKING CHANGE
  .github/workflows/integration.yml
  .github/workflows/unit.yml
  .gitignore
  README.md
  backend/Gemfile
  backend/Gemfile.lock
  backend/config/database.yml
  backend/db/migrate/20181113120438_create_users.rb
  backend/db/migrate/20181120113857_create_titles.rb
  backend/db/migrate/20181120114623_create_books.rb
  backend/db/migrate/20181121120753_create_active_storage_tables.active_storage.rb
  backend/db/migrate/20191216141505_create_reviews.rb
  backend/db/migrate/20191218133143_add_subject_table.rb
  backend/db/schema.rb
  docker-compose.yml
Labels: comp: backend, dependencies, type:performance🐎

#560 LoanFormComponent are refactored
  frontend/src/components/LoanFormComponent.vue
  frontend/src/components/__tests__/LoanFormComponent.spec.ts
Labels: type:refactor 🔨
