Repository itggot-TE4/Yabs, pull requests merged in 2020-01, with the labels that each got.

#299 hotfixing hard coded user ids after new year uid updates
  backend/db/seeds.rb
  backend/test/controllers/users_controller_test.rb
  backend/test/fixtures/books.yml
  backend/test/fixtures/loans.yml
  backend/test/fixtures/reviews.yml
  backend/test/fixtures/titles.yml
  backend/test/fixtures/users.yml
Labels: bug

#257 Feature/137 book status
  .gitignore
  backend/app/controllers/api/v1/books_controller.rb
  backend/app/views/books/_book.json.jbuilder
  backend/db/migrate/20200108094255_rename_books_status_to_condition.rb
  backend/db/seeds.rb
  backend/test/controllers/books_controller_test.rb
  frontend/src/api/books.ts
  frontend/src/api/titles.ts
  frontend/src/components/BookConditionComponent.vue
  frontend/src/components/BookFormComponent.vue
  frontend/src/components/BookListComponent.vue
  frontend/src/router.ts
  frontend/src/store/modules/BooksModule.ts
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/types.ts
  frontend/src/views/EditBookView.vue
  frontend/src/views/FindView.vue
  frontend/src/views/index.ts
Labels: discussion

#302 Hotfixed unit tests
  backend/db/schema.rb
  backend/test/fixtures/books.yml
  backend/test/fixtures/loans.yml
  backend/test/fixtures/reviews.yml
  backend/test/fixtures/titles.yml
  backend/test/fixtures/users.yml
  frontend/src/views/FindView.vue
Labels: bug

#307 Fixed remaining lint issues
  frontend/.eslintignore
  frontend/package.json
  frontend/src/components/AddLoan.vue
  frontend/src/components/GoogleLogin.vue
  frontend/src/components/ListComponent.vue
  frontend/src/helpers/testFactoryHelpers.ts
  frontend/src/main.ts
  frontend/src/views/Start.vue
Labels: enhancement, frontend

#305 fixed wrongly displayed error message
  backend/db/seeds.rb
Labels: backend, bug

#303 refactored api-calls
  frontend/src/api/books.ts
  frontend/src/api/loans.ts
  frontend/src/api/titles.ts
  frontend/src/api/users.ts
  frontend/src/services/api/APIRequest.ts
  frontend/src/services/api/books.ts
  frontend/src/services/api/loans.ts
  frontend/src/services/api/titles.ts
  frontend/src/services/api/users.ts
  frontend/src/store/modules/BooksModule.ts
  frontend/src/store/modules/LoansModule.ts
  frontend/src/store/modules/TitlesModule.ts
  frontend/src/store/modules/UsersModule.ts
Labels: enhancement

#313 Feature/300 add user routing
  frontend/src/components/UserListComponent.vue
Labels: blue, enhancement, frontend, red

#316 Changed status to condition
  frontend/cypress/integration/createTitleAndBooks.js
Labels: bug

#315 now tests if name/klass/role shows up on ProfileView
  frontend/src/views/ProfileView.vue
  frontend/src/views/__tests__/ProfileView.spec.ts
  frontend/src/views/index.ts
Labels: enhancement

#317 allow uninitialized note
  frontend/src/components/BookConditionComponent.vue
Labels: bug

#319 angered the linter, made warnings into errors
  frontend/.eslintrc.js
  frontend/yarn.lock
Labels: enhancement

#323 videos and screenshots no longer pushed to github
  .gitignore
  frontend/cypress/videos/AddIDCard.spec.js.mp4
  frontend/cypress/videos/FirstPageTests.spec.js.mp4
Labels: 1p, enhancement, red

#321 Fixed styling
  frontend/src/components/CanvasContainer.vue
Labels: 1p, bug, red

#320 Feature/217 connect subjects
  backend/app/assets/javascripts/subjects.coffee
  backend/app/assets/stylesheets/scaffolds.scss
  backend/app/assets/stylesheets/subjects.scss
  backend/app/controllers/api/v1/subjects_controller.rb
  backend/app/controllers/api/v1/titles_controller.rb
  backend/app/helpers/subjects_helper.rb
  backend/app/models/book.rb
  backend/app/models/responsibility.rb
  backend/app/models/subject.rb
  backend/app/models/title.rb
  backend/app/models/user.rb
  backend/app/views/subjects/_subject.json.jbuilder
  backend/app/views/subjects/index.json.jbuilder
  backend/app/views/subjects/show.json.jbuilder
  backend/config/routes.rb
  backend/db/migrate/20191218133143_add_subject_table.rb
  backend/db/migrate/20191218133430_add_subject_ref_to_titles.rb
  backend/db/migrate/20191218150544_create_subjects.rb
  backend/db/migrate/20200109092304_create_responsibilities.rb
  backend/db/schema.rb
  backend/db/seeds.rb
  backend/test/controllers/subjects_controller_test.rb
  backend/test/controllers/titles_controller_test.rb
  backend/test/fixtures/responsibilities.yml
  backend/test/fixtures/subjects.yml
  backend/test/fixtures/titles.yml
  backend/test/models/responsibility_test.rb
  backend/test/models/subject_test.rb
Labels: 8p, backend, red

#324 added tests for BookFormComponent, TitleFormComponent, LoanFormComponent
  frontend/src/components/BookFormComponent.vue
  frontend/src/components/ListComponent.vue
  frontend/src/components/LoanFormComponent.vue
  frontend/src/components/TitleFormComponent.vue
  frontend/src/components/__tests__/BookFormComponent.spec.ts
  frontend/src/components/__tests__/ListComponent.spec.ts
  frontend/src/components/__tests__/LoanFormComponent.spec.ts
  frontend/src/components/__tests__/TitleFormComponent.spec.ts
  frontend/src/helpers/testFactoryHelpers.ts
Labels: blue, frontend

#330 changed from www to api
  .github/workflows/integration.yml
Labels: bug

#331 you can now change the roles of staff
  backend/app/controllers/api/v1/users_controller.rb
  frontend/src/helpers/RoleChecker.ts
  frontend/src/helpers/__tests__/RoleChecker.spec.ts
  frontend/src/router.ts
  frontend/src/services/api/users.ts
  frontend/src/store/modules/UsersModule.ts
  frontend/src/types.ts
  frontend/src/views/AdminUsersView.vue
  frontend/src/views/AdminView.vue
  frontend/src/views/index.ts
Labels: backend, enhancement, frontend

#334 Feature/298 create library view
  backend/app/controllers/api/v1/loans_controller.rb
  backend/app/policies/loan_policy.rb
  frontend/src/components/LibraryLoanComponent.vue
  frontend/src/components/ReturnLoanComponent.vue
  frontend/src/router.ts
  frontend/src/services/api/APIRequest.ts
  frontend/src/store/modules/LoansModule.ts
  frontend/src/views/LibraryView.vue
  frontend/src/views/index.ts
Labels: blue, enhancement
